<?= $this->extend('Layout/template');?>
<?= $this->section('content') ?>
<div class="container">
    <h2 class="text-center">Rangkaian BMKG Goes to School Kabupaten Buleleng 5-6 September 2023</h2>
    <div class="container d-flex justify-content-center">
        <img src="<?= base_url('gambar/artikel/artikel_20230905_1.jpg') ?>" alt="">
    </div>
    <br>
    <p>Sebagai tidak lanjut kegiatan Sekolah Lapang Gempabumi yang diadakan di Kabupaten Buleleng wilayah Desa Pengastulan, Stasiun Geofisika Denpasar melakukan kegiatan BMKG Goes To School. Dalam pelaksanaan BMKG Goes to School ini, Stasiun Geofisika Denpasar menurunkan 2 tim. Kegiatan ini dilaksanakan pada 5 September 2023 di SMP N 4 seririt, SMA N 1 Seririt, SD N 1 Kalianget dan SMA Saraswati Seririt. Selanjutnya pada 6 September 2023 dilaksanakan di SD N 2 Seririt, SMPN 1 Seririt, SD N 3 Pengastulan dan SD N 1 Pengastulan. Jumlah peserta yang mengikuti rangkaian kegiatan BMKG Goes To School berjumlah 400 siswa dan 24 guru. Rangkaian kegiatan ini meliputi penyampaian sosialisasi dan mitigasi Gempabumi dan Tsunami, pembagian tas siaga tsunami serta simulasi.</p>
    <p>Kegiatan sosialisasi dan simulasi mitigasi bencana “Goes To School” merupakan program “BMKG GOES TO SCHOOL” yang dilaksanakan oleh Stasiun Geofisika Denpasar.  Kegiatan ini bertujuan memberikan pemahaman akan potensi gempabumi dan tsunami serta memberikan pengetahuan tentang pentingnya upaya mitigasi bencana untuk mengurangi dampak bencana gempabumi dan tsunami di wilayah Seririt melalui penyampaian materi tentang potensi gempabumi dan tsunami dan simulasi (drill) gempabumi dan tsunami.</p>
    <p>Simulasi gempabumi kuat dilakukan untuk melatih kesiapsiagaan peserta apabila terjadi gempabumi di wilayahnya. Simulasi dimulai dengan skenario sederhana berupa kegiatan di sekolah yang berlangsung seperti biasa, kemudian diikuti dengan peringatan “Gempa! Gempa! Gempa!” sebagai pertanda terjadi gempabumi, kemudian Tim BMKG Stasiun Geofisika Denpasar memberikan informasi gempabumi yang terjadi dan potensi tsunami. Peserta melakukan perlindungan diri di tempat masing-masing dengan cara melindungi kepala seperti yang telah dilatih. Setelah aba-aba “gempabumi mereda!” sebagai tanda berakhir nya gempabumi peserta keluar dari kelas untuk menuju ke titik kumpul yang telah disepakati sebelumnya.</p>
    <p> Kegiatan ini diharapkan dapat dilaksanakan secara rutin dan berkesinambungan khususnya di wilayah Provinsi Bali mengingat wilayah Bali merupakan salah satu daerah yang memiliki tingkat kegempaan yang tinggi dan berpotensi memicu terjadinya tsunami. </p>
</div>
<?= $this->endSection() ?>